package br.com.careermatcher.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum PesosRanker {
    SENIORIDADE_CUMPRIDA(6),
    SENIORIDADE_NAO_CUMPRIDA(-2),

    LOCALIDADE_CUMPRIDA(2),
    LOCALIDADE_NAO_CUMPRIDA(-2),

    EXPERIENCIA_SENIORIODADE_ACIMA(4),
    EXPERIENCIA_SENIORIODADE_ABAIXO(1),
    EXPERIENCIA_TEMPO(3),

    GRADUACAO_CURSO_CUMPRIDO(2),
    GRADUACAO_INSTITUICAO_CUMPRIDO(2),
    GRADUACAO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    GRADUACAO_NAO_CUMPRIDA(-2),

    MESTRADO_CURSO_OU_SUBAREA_CUMPRIDO(2),
    MESTRADO_INSTITUICAO_CUMPRIDA(2),
    MESTRADO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    MESTRADO_NAO_CUMPRIDO(-2),

    DOUTORADO_CURSO_OU_SUBAREA_CUMPRIDO(2),
    DOUTORADO_INSTITUICAO_CUMPRIDA(2),
    DOUTORADO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    DOUTORADO_NAO_CUMPRIDO(-2),

    POSDOUTORADO_CURSO_OU_SUBAREA_CUMPRIDO(2),
    POSDOUTORADO_INSTITUICAO_CUMPRIDA(2),
    POSDOUTORADO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    POSDOUTORADO_NAO_CUMPRIDO(-2)

    ;
    @Getter
    private final int peso;
}
