package br.com.careermatcher.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum PesosRanker {
    SENIORIDADE_CUMPRIDA(4),
    SENIORIDADE_ABAIXO(-1),
    SENIORIODADE_ACIMA(1),

    LOCALIDADE_CUMPRIDA(3),
    LOCALIDADE_NAO_CUMPRIDA(-3),

    EXPERIENCIA_SENIORIODADE_ACIMA(1),
    EXPERIENCIA_SENIORIODADE_CUMPRIDA(4),
    EXPERIENCIA_SENIORIODADE_ABAIXO(2),
    EXPERIENCIA_TEMPO(3),
    EXPERIENCIA_NAO_CUMPRIDA(-3),

    VAGA_MODALIDADE_REMOTO(6),

    COMPETENCIA_CUMPRIDA(3),
    COMPETENCIA_NAO_CUMPRIDA(-2),

    GRADUACAO_CURSO_CUMPRIDO(4),
    GRADUACAO_INSTITUICAO_CUMPRIDO(2),
    GRADUACAO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    GRADUACAO_NAO_CUMPRIDA(-4),

    MESTRADO_CURSO_OU_SUBAREA_CUMPRIDO(4),
    MESTRADO_INSTITUICAO_CUMPRIDA(2),
    MESTRADO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    MESTRADO_NAO_CUMPRIDO(-4),

    DOUTORADO_CURSO_OU_SUBAREA_CUMPRIDO(4),
    DOUTORADO_INSTITUICAO_CUMPRIDA(2),
    DOUTORADO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    DOUTORADO_NAO_CUMPRIDO(-4),

    POSDOUTORADO_CURSO_OU_SUBAREA_CUMPRIDO(4),
    POSDOUTORADO_INSTITUICAO_CUMPRIDA(2),
    POSDOUTORADO_TEMPO_CONCLUIDO_CUMPRIDO(2),
    POSDOUTORADO_NAO_CUMPRIDO(-4);

    @Getter
    private final int peso;
}
