package br.com.careermatcher.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
public enum PesosRanker {
    SENIORIDADE_CUMPRIDA(2),
    SENIORIDADE_ABAIXO(-1),
    SENIORIODADE_ACIMA(1),

    LOCALIDADE_CUMPRIDA(1),
    LOCALIDADE_NAO_CUMPRIDA(-1),

    EXPERIENCIA_SENIORIODADE_ACIMA(1),
    EXPERIENCIA_SENIORIODADE_CUMPRIDA(2),
    EXPERIENCIA_SENIORIODADE_ABAIXO(1),
    EXPERIENCIA_TEMPO(1),
    EXPERIENCIA_NAO_CUMPRIDA(-1),

    VAGA_MODALIDADE_REMOTO(6),

    COMPETENCIA_CUMPRIDA(10),
    COMPETENCIA_NAO_CUMPRIDA(-1),

    GRADUACAO_CURSO_CUMPRIDO(1),
    GRADUACAO_INSTITUICAO_CUMPRIDO(1),
    GRADUACAO_TEMPO_CONCLUIDO_CUMPRIDO(1),
    GRADUACAO_NAO_CUMPRIDA(-1),

    MESTRADO_CURSO_OU_SUBAREA_CUMPRIDO(1),
    MESTRADO_INSTITUICAO_CUMPRIDA(1),
    MESTRADO_TEMPO_CONCLUIDO_CUMPRIDO(1),
    MESTRADO_NAO_CUMPRIDO(-1),

    DOUTORADO_CURSO_OU_SUBAREA_CUMPRIDO(1),
    DOUTORADO_INSTITUICAO_CUMPRIDA(1),
    DOUTORADO_TEMPO_CONCLUIDO_CUMPRIDO(1),
    DOUTORADO_NAO_CUMPRIDO(-1),

    POSDOUTORADO_CURSO_OU_SUBAREA_CUMPRIDO(1),
    POSDOUTORADO_INSTITUICAO_CUMPRIDA(1),
    POSDOUTORADO_TEMPO_CONCLUIDO_CUMPRIDO(1),
    POSDOUTORADO_NAO_CUMPRIDO(-1)

    ;
    @Getter
    private final int peso;
}
